-- Catalog reference data: levels, tags, collections.
-- Source: tasks-mockup/assets/js/data-core.js (generated, do not edit by hand).

CREATE TABLE IF NOT EXISTS levels (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  css_class   TEXT NOT NULL DEFAULT '',
  profile     TEXT NOT NULL DEFAULT '',
  time_hint   TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  active      BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS tags (
  id        TEXT PRIMARY KEY,
  name      TEXT NOT NULL,
  category  TEXT NOT NULL DEFAULT '',
  synonyms  TEXT[] NOT NULL DEFAULT '{}',
  active    BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS collections (
  id          TEXT PRIMARY KEY,
  title       TEXT NOT NULL,
  tagline     TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  icon        TEXT NOT NULL DEFAULT '',
  audience    TEXT NOT NULL DEFAULT '',
  task_ids    TEXT[] NOT NULL DEFAULT '{}',
  active      BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO levels (id, name, css_class, profile, time_hint, description, active) VALUES ('easy', 'Лёгкий', 'level-easy', 'Junior / Junior+', '15–25 мин', 'Базовая задача на 15–25 минут. Проверяет, что кандидат владеет терминологией и умеет оформить простую вещь без подсказок.', TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, css_class = EXCLUDED.css_class, profile = EXCLUDED.profile, time_hint = EXCLUDED.time_hint, description = EXCLUDED.description, active = EXCLUDED.active;
INSERT INTO levels (id, name, css_class, profile, time_hint, description, active) VALUES ('medium', 'Средний', 'level-medium', 'Middle', '30–45 мин', 'Задача с неоднозначностью: данных не хватает, есть конфликт ограничений. Проверяет самостоятельность и полноту проработки.', TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, css_class = EXCLUDED.css_class, profile = EXCLUDED.profile, time_hint = EXCLUDED.time_hint, description = EXCLUDED.description, active = EXCLUDED.active;
INSERT INTO levels (id, name, css_class, profile, time_hint, description, active) VALUES ('hard', 'Сложный', 'level-hard', 'Senior / Lead', '45–90 мин', 'Проектная задача на 45–90 минут: распределённые системы, компромиссы, эксплуатация. Проверяет системное мышление и опыт.', TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, css_class = EXCLUDED.css_class, profile = EXCLUDED.profile, time_hint = EXCLUDED.time_hint, description = EXCLUDED.description, active = EXCLUDED.active;

INSERT INTO tags (id, name, category, synonyms, active) VALUES ('rest-api', 'REST API', 'api', ARRAY['rest','http api'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('soap', 'SOAP', 'api', ARRAY['wsdl','xml'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('graphql', 'GraphQL', 'api', '{}', TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('api-design', 'Проектирование API', 'api', ARRAY['openapi','swagger','контракт'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('versioning', 'Версионирование', 'api', ARRAY['versioning'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('idempotency', 'Идемпотентность', 'api', ARRAY['idempotency'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('integrations', 'Интеграции', 'integration', ARRAY['integration'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('kafka', 'Kafka', 'integration', ARRAY['брокер','очередь','topic'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('rabbitmq', 'RabbitMQ', 'integration', ARRAY['amqp'], FALSE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('async', 'Асинхронное взаимодействие', 'integration', ARRAY['event-driven','событий'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('webhook', 'Webhook', 'integration', ARRAY['callback'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('files', 'Файловый обмен', 'integration', ARRAY['sftp','csv','xml-файл'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('architecture', 'Архитектура', 'architecture', ARRAY['arch'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('system-design', 'Системный дизайн', 'architecture', '{}', TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('microservices', 'Микросервисы', 'architecture', '{}', TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('saga', 'Сага / распределённые транзакции', 'architecture', ARRAY['2pc','компенсаци'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('cqrs', 'CQRS / событийная модель', 'architecture', ARRAY['event sourcing'], FALSE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('ddd', 'DDD и границы контекстов', 'architecture', ARRAY['bounded context'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('cache', 'Кэширование', 'architecture', ARRAY['redis','cache'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('sql', 'SQL', 'data', ARRAY['select','join'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('db-design', 'Проектирование БД', 'data', ARRAY['схема бд'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('normalization', 'Нормализация', 'data', ARRAY['нф','3нф'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('indexes', 'Индексы и производительность', 'data', ARRAY['индекс','explain'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('transactions', 'Транзакции и блокировки', 'data', ARRAY['isolation','mvcc'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('migration', 'Миграции данных', 'data', ARRAY['migration'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('dwh', 'DWH / витрины', 'data', ARRAY['хранилище','etl','витрина'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('nosql', 'NoSQL', 'data', ARRAY['mongo','document store'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('requirements', 'Требования', 'requirements', ARRAY['тз','srs'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('user-story', 'User Story', 'requirements', ARRAY['пользовательская история'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('acceptance', 'Критерии приёмки', 'requirements', ARRAY['acceptance criteria','bdd'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('use-case', 'Use Case / сценарии', 'requirements', ARRAY['сценарий использования'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('edge-cases', 'Граничные случаи и ошибки', 'requirements', ARRAY['альтернативные сценарии','edge case'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('nfr', 'Нефункциональные требования', 'requirements', ARRAY['нфт','sla','нагрузка'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('uml', 'UML', 'modeling', '{}', TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('sequence', 'Sequence-диаграмма', 'modeling', ARRAY['диаграмма последовательности'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('bpmn', 'BPMN', 'modeling', ARRAY['бизнес-процесс'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('er', 'ER-диаграмма', 'modeling', ARRAY['сущность-связь'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('state', 'Диаграмма состояний', 'modeling', ARRAY['state machine'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('component', 'Компонентная схема', 'modeling', ARRAY['c4','deployment'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('reliability', 'Надёжность', 'reliability', ARRAY['отказоустойчивость'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('retry', 'Таймауты и ретраи', 'reliability', ARRAY['retry','timeout','circuit breaker'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('observability', 'Логирование и мониторинг', 'reliability', ARRAY['метрики системы','tracing','alert'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('degradation', 'Деградация и план Б', 'reliability', ARRAY['fallback','graceful'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('security', 'Безопасность', 'security', '{}', TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('oauth', 'Аутентификация / OAuth 2.0', 'security', ARRAY['jwt','токен','auth'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('pd', 'Персональные данные (152-ФЗ)', 'security', ARRAY['pii','gdpr'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('roles', 'Роли и права доступа', 'security', ARRAY['rbac','доступ'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('stakeholders', 'Стейкхолдеры', 'process', ARRAY['заказчик'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('conflict', 'Конфликты требований', 'process', ARRAY['переговоры','согласование позиций','эскалация'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('agile', 'Agile / Scrum', 'process', ARRAY['спринт'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('estimation', 'Оценка и декомпозиция', 'process', ARRAY['декомпозиция','оценка'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('discovery', 'Discovery и интервью', 'process', ARRAY['custdev','исследование'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('metrics', 'Продуктовые метрики', 'analytics', ARRAY['kpi'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('ab', 'A/B-эксперименты', 'analytics', ARRAY['ab test'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('reports', 'Отчётность', 'analytics', ARRAY['дашборд','bi'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('unit-economics', 'Юнит-экономика', 'analytics', '{}', FALSE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('testing', 'Тестирование и QA', 'quality', ARRAY['qa'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('data-quality', 'Качество данных', 'quality', ARRAY['dq','валидация данных','чистота данных'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('docs', 'Документация', 'quality', ARRAY['confluence','wiki'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;
INSERT INTO tags (id, name, category, synonyms, active) VALUES ('release', 'Выкатка и feature flags', 'quality', ARRAY['feature toggle','релиз'], TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, synonyms = EXCLUDED.synonyms, active = EXCLUDED.active;

INSERT INTO collections (id, title, tagline, description, icon, audience, task_ids, active) VALUES ('integrations', 'Интеграции', 'REST, SOAP, брокеры, файловый обмен', 'Задачи про то, как системы разговаривают друг с другом: контракты, идемпотентность, таймауты и ретраи, гарантии доставки, разбор ошибок. Самый частый блок на собеседованиях системного аналитика.', '⇄', 'SA / BA, Middle и выше', ARRAY['int-timeouts','int-idempotency','int-soap-migration','int-kafka-events','int-oauth-partner'], TRUE) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, tagline = EXCLUDED.tagline, description = EXCLUDED.description, icon = EXCLUDED.icon, audience = EXCLUDED.audience, task_ids = EXCLUDED.task_ids, active = EXCLUDED.active;
INSERT INTO collections (id, title, tagline, description, icon, audience, task_ids, active) VALUES ('system-design', 'Проектирование и системный дизайн', 'Архитектура, границы сервисов, состояния', 'Проектирование системы с нуля: границы сервисов, модель данных, состояния сущностей, синхронные и асинхронные потоки. Проверяем, умеете ли вы принимать решения и обосновывать компромиссы.', '◧', 'SA, Middle / Senior', ARRAY['des-er-catalog','des-order-state','des-notifications','des-loyalty'], TRUE) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, tagline = EXCLUDED.tagline, description = EXCLUDED.description, icon = EXCLUDED.icon, audience = EXCLUDED.audience, task_ids = EXCLUDED.task_ids, active = EXCLUDED.active;
INSERT INTO collections (id, title, tagline, description, icon, audience, task_ids, active) VALUES ('databases', 'Базы данных и SQL', 'Схемы, запросы, производительность, миграции', 'От простого SELECT до плана миграции на сотни миллионов строк: нормализация, индексы, транзакции, витрины и качество данных. Практика, которую реально дают на технических экранах.', '⛁', 'SA / BA / Data-ориентированные роли', ARRAY['db-slow-report','db-normalization','db-dwh-metrics','db-migration'], TRUE) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, tagline = EXCLUDED.tagline, description = EXCLUDED.description, icon = EXCLUDED.icon, audience = EXCLUDED.audience, task_ids = EXCLUDED.task_ids, active = EXCLUDED.active;
INSERT INTO collections (id, title, tagline, description, icon, audience, task_ids, active) VALUES ('requirements', 'Требования и коммуникации', 'Сбор, формализация, конфликты стейкхолдеров', 'Превращение «хотим как у конкурентов» в требования, по которым можно разрабатывать: user stories, критерии приёмки, альтернативные сценарии, работа с конфликтом заказчика и рисков.', '✎', 'BA / SA, Junior и выше', ARRAY['req-vague-feature','req-api-contract','req-stakeholder-conflict'], TRUE) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, tagline = EXCLUDED.tagline, description = EXCLUDED.description, icon = EXCLUDED.icon, audience = EXCLUDED.audience, task_ids = EXCLUDED.task_ids, active = EXCLUDED.active;
INSERT INTO collections (id, title, tagline, description, icon, audience, task_ids, active) VALUES ('interview-warmup', 'Разминка перед собеседованием', '6 задач на 2–3 вечера', 'Короткий набор, который покрывает типовые вопросы технического экрана: контракт API, идемпотентность, медленный запрос, модель состояний, бизнес-процесс и нефункциональные требования.', '⚡', 'Все уровни', ARRAY['req-vague-feature','int-timeouts','db-slow-report','des-order-state','int-idempotency','req-api-contract'], TRUE) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, tagline = EXCLUDED.tagline, description = EXCLUDED.description, icon = EXCLUDED.icon, audience = EXCLUDED.audience, task_ids = EXCLUDED.task_ids, active = EXCLUDED.active;
INSERT INTO collections (id, title, tagline, description, icon, audience, task_ids, active) VALUES ('fintech', 'Финтех и платежи', 'Деньги, согласованность, аудит', 'Доменная подборка: платёжные потоки, согласованность данных, идемпотентность списаний, безопасность и требования регуляторов. Подходит, если собес в банк или платёжный сервис.', '₽', 'SA / BA, Middle+', ARRAY['int-idempotency','int-kafka-events','int-oauth-partner','db-migration','des-loyalty'], TRUE) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, tagline = EXCLUDED.tagline, description = EXCLUDED.description, icon = EXCLUDED.icon, audience = EXCLUDED.audience, task_ids = EXCLUDED.task_ids, active = EXCLUDED.active;
