-- Task cards (catalog list summary). Full bodies arrive in Phase 2.
-- Source: tasks-mockup/assets/js/data-tasks-*.js (generated, do not edit by hand).

CREATE TABLE IF NOT EXISTS tasks (
  id          TEXT PRIMARY KEY,
  title       TEXT NOT NULL,
  level_id    TEXT NOT NULL REFERENCES levels (id),
  tags        TEXT[] NOT NULL DEFAULT '{}',
  status      TEXT NOT NULL DEFAULT 'published',
  time_min    INTEGER NOT NULL DEFAULT 30,
  solved_rate INTEGER NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO tasks (id, title, level_id, tags, status, time_min, solved_rate) VALUES ('int-timeouts', 'Нестабильный внешний сервис: таймауты и повторные попытки', 'easy', ARRAY['integrations','rest-api','retry','reliability','nfr'], 'published', 20, 71) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, level_id = EXCLUDED.level_id, tags = EXCLUDED.tags, time_min = EXCLUDED.time_min, solved_rate = EXCLUDED.solved_rate, updated_at = now();
INSERT INTO tasks (id, title, level_id, tags, status, time_min, solved_rate) VALUES ('int-idempotency', 'Идемпотентное списание: платёжный запрос к REST API', 'medium', ARRAY['rest-api','idempotency','api-design','integrations','edge-cases','transactions'], 'published', 40, 44) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, level_id = EXCLUDED.level_id, tags = EXCLUDED.tags, time_min = EXCLUDED.time_min, solved_rate = EXCLUDED.solved_rate, updated_at = now();
INSERT INTO tasks (id, title, level_id, tags, status, time_min, solved_rate) VALUES ('int-soap-migration', 'Перевод интеграции с SOAP на REST без остановки потока', 'medium', ARRAY['soap','rest-api','integrations','versioning','migration','api-design'], 'published', 45, 38) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, level_id = EXCLUDED.level_id, tags = EXCLUDED.tags, time_min = EXCLUDED.time_min, solved_rate = EXCLUDED.solved_rate, updated_at = now();
INSERT INTO tasks (id, title, level_id, tags, status, time_min, solved_rate) VALUES ('int-kafka-events', 'Событийная интеграция заказа: Kafka, гарантии и согласованность', 'hard', ARRAY['kafka','async','architecture','saga','integrations','reliability','observability'], 'published', 75, 23) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, level_id = EXCLUDED.level_id, tags = EXCLUDED.tags, time_min = EXCLUDED.time_min, solved_rate = EXCLUDED.solved_rate, updated_at = now();
INSERT INTO tasks (id, title, level_id, tags, status, time_min, solved_rate) VALUES ('int-oauth-partner', 'Доступ партнёра к нашему API: OAuth 2.0, лимиты и аудит', 'hard', ARRAY['oauth','security','rest-api','api-design','roles','nfr','observability'], 'published', 60, 27) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, level_id = EXCLUDED.level_id, tags = EXCLUDED.tags, time_min = EXCLUDED.time_min, solved_rate = EXCLUDED.solved_rate, updated_at = now();
INSERT INTO tasks (id, title, level_id, tags, status, time_min, solved_rate) VALUES ('des-er-catalog', 'Модель данных каталога товаров: от Excel-таблицы к схеме', 'easy', ARRAY['db-design','er','normalization','uml','requirements'], 'published', 25, 66) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, level_id = EXCLUDED.level_id, tags = EXCLUDED.tags, time_min = EXCLUDED.time_min, solved_rate = EXCLUDED.solved_rate, updated_at = now();
INSERT INTO tasks (id, title, level_id, tags, status, time_min, solved_rate) VALUES ('des-order-state', 'Модель состояний заказа и переходы между ними', 'medium', ARRAY['state','uml','requirements','edge-cases','use-case','system-design'], 'published', 35, 49) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, level_id = EXCLUDED.level_id, tags = EXCLUDED.tags, time_min = EXCLUDED.time_min, solved_rate = EXCLUDED.solved_rate, updated_at = now();
INSERT INTO tasks (id, title, level_id, tags, status, time_min, solved_rate) VALUES ('des-notifications', 'Сервис уведомлений: каналы, предпочтения, дедупликация', 'medium', ARRAY['architecture','system-design','kafka','async','requirements','observability','pd'], 'published', 45, 41) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, level_id = EXCLUDED.level_id, tags = EXCLUDED.tags, time_min = EXCLUDED.time_min, solved_rate = EXCLUDED.solved_rate, updated_at = now();
INSERT INTO tasks (id, title, level_id, tags, status, time_min, solved_rate) VALUES ('des-loyalty', 'Система лояльности ритейлера: начисление и списание баллов', 'hard', ARRAY['system-design','architecture','ddd','transactions','integrations','saga','metrics','edge-cases'], 'published', 90, 18) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, level_id = EXCLUDED.level_id, tags = EXCLUDED.tags, time_min = EXCLUDED.time_min, solved_rate = EXCLUDED.solved_rate, updated_at = now();
INSERT INTO tasks (id, title, level_id, tags, status, time_min, solved_rate) VALUES ('db-slow-report', 'Отчёт по продажам собирается 40 минут: найти причину', 'easy', ARRAY['sql','indexes','dwh','reports','observability'], 'published', 25, 58) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, level_id = EXCLUDED.level_id, tags = EXCLUDED.tags, time_min = EXCLUDED.time_min, solved_rate = EXCLUDED.solved_rate, updated_at = now();
INSERT INTO tasks (id, title, level_id, tags, status, time_min, solved_rate) VALUES ('db-normalization', 'Таблица заявок «как в Excel» → нормальная схема', 'medium', ARRAY['normalization','db-design','sql','er','migration','requirements'], 'published', 40, 47) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, level_id = EXCLUDED.level_id, tags = EXCLUDED.tags, time_min = EXCLUDED.time_min, solved_rate = EXCLUDED.solved_rate, updated_at = now();
INSERT INTO tasks (id, title, level_id, tags, status, time_min, solved_rate) VALUES ('db-dwh-metrics', 'Витрина выручки: данные, качество и SLA отчётности', 'medium', ARRAY['dwh','sql','metrics','reports','requirements','data-quality'], 'published', 45, 33) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, level_id = EXCLUDED.level_id, tags = EXCLUDED.tags, time_min = EXCLUDED.time_min, solved_rate = EXCLUDED.solved_rate, updated_at = now();
INSERT INTO tasks (id, title, level_id, tags, status, time_min, solved_rate) VALUES ('db-migration', 'Миграция 200 млн строк без простоя: план и риски', 'hard', ARRAY['migration','sql','architecture','reliability','release','nfr','observability'], 'published', 80, 16) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, level_id = EXCLUDED.level_id, tags = EXCLUDED.tags, time_min = EXCLUDED.time_min, solved_rate = EXCLUDED.solved_rate, updated_at = now();
INSERT INTO tasks (id, title, level_id, tags, status, time_min, solved_rate) VALUES ('req-vague-feature', '«Хотим как у конкурентов»: из идеи в требования', 'easy', ARRAY['requirements','user-story','acceptance','discovery','stakeholders','use-case'], 'published', 25, 62) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, level_id = EXCLUDED.level_id, tags = EXCLUDED.tags, time_min = EXCLUDED.time_min, solved_rate = EXCLUDED.solved_rate, updated_at = now();
INSERT INTO tasks (id, title, level_id, tags, status, time_min, solved_rate) VALUES ('req-api-contract', 'Контракт API для мобильного приложения: версии, пагинация, ошибки', 'medium', ARRAY['rest-api','api-design','requirements','versioning','edge-cases','nfr'], 'published', 40, 42) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, level_id = EXCLUDED.level_id, tags = EXCLUDED.tags, time_min = EXCLUDED.time_min, solved_rate = EXCLUDED.solved_rate, updated_at = now();
INSERT INTO tasks (id, title, level_id, tags, status, time_min, solved_rate) VALUES ('req-stakeholder-conflict', 'Продажи против рисков: конфликт требований и решение аналитика', 'medium', ARRAY['stakeholders','requirements','conflict','acceptance','nfr','roles','metrics'], 'published', 35, 36) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, level_id = EXCLUDED.level_id, tags = EXCLUDED.tags, time_min = EXCLUDED.time_min, solved_rate = EXCLUDED.solved_rate, updated_at = now();
